// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/storage/v1/storage.proto

package io.nitric.proto.storage.v1;

/**
 * Protobuf type {@code nitric.storage.v1.StorageListFilesResponse}
 */
public final class StorageListFilesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nitric.storage.v1.StorageListFilesResponse)
    StorageListFilesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StorageListFilesResponse.newBuilder() to construct.
  private StorageListFilesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StorageListFilesResponse() {
    files_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StorageListFilesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StorageListFilesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              files_ = new java.util.ArrayList<io.nitric.proto.storage.v1.File>();
              mutable_bitField0_ |= 0x00000001;
            }
            files_.add(
                input.readMessage(io.nitric.proto.storage.v1.File.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        files_ = java.util.Collections.unmodifiableList(files_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.nitric.proto.storage.v1.Storages.internal_static_nitric_storage_v1_StorageListFilesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.nitric.proto.storage.v1.Storages.internal_static_nitric_storage_v1_StorageListFilesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.nitric.proto.storage.v1.StorageListFilesResponse.class, io.nitric.proto.storage.v1.StorageListFilesResponse.Builder.class);
  }

  public static final int FILES_FIELD_NUMBER = 1;
  private java.util.List<io.nitric.proto.storage.v1.File> files_;
  /**
   * <pre>
   * keys of the files in the bucket
   * </pre>
   *
   * <code>repeated .nitric.storage.v1.File files = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.nitric.proto.storage.v1.File> getFilesList() {
    return files_;
  }
  /**
   * <pre>
   * keys of the files in the bucket
   * </pre>
   *
   * <code>repeated .nitric.storage.v1.File files = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.nitric.proto.storage.v1.FileOrBuilder> 
      getFilesOrBuilderList() {
    return files_;
  }
  /**
   * <pre>
   * keys of the files in the bucket
   * </pre>
   *
   * <code>repeated .nitric.storage.v1.File files = 1;</code>
   */
  @java.lang.Override
  public int getFilesCount() {
    return files_.size();
  }
  /**
   * <pre>
   * keys of the files in the bucket
   * </pre>
   *
   * <code>repeated .nitric.storage.v1.File files = 1;</code>
   */
  @java.lang.Override
  public io.nitric.proto.storage.v1.File getFiles(int index) {
    return files_.get(index);
  }
  /**
   * <pre>
   * keys of the files in the bucket
   * </pre>
   *
   * <code>repeated .nitric.storage.v1.File files = 1;</code>
   */
  @java.lang.Override
  public io.nitric.proto.storage.v1.FileOrBuilder getFilesOrBuilder(
      int index) {
    return files_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < files_.size(); i++) {
      output.writeMessage(1, files_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < files_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, files_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.nitric.proto.storage.v1.StorageListFilesResponse)) {
      return super.equals(obj);
    }
    io.nitric.proto.storage.v1.StorageListFilesResponse other = (io.nitric.proto.storage.v1.StorageListFilesResponse) obj;

    if (!getFilesList()
        .equals(other.getFilesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFilesCount() > 0) {
      hash = (37 * hash) + FILES_FIELD_NUMBER;
      hash = (53 * hash) + getFilesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.storage.v1.StorageListFilesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.nitric.proto.storage.v1.StorageListFilesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nitric.storage.v1.StorageListFilesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nitric.storage.v1.StorageListFilesResponse)
      io.nitric.proto.storage.v1.StorageListFilesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nitric.proto.storage.v1.Storages.internal_static_nitric_storage_v1_StorageListFilesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nitric.proto.storage.v1.Storages.internal_static_nitric_storage_v1_StorageListFilesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nitric.proto.storage.v1.StorageListFilesResponse.class, io.nitric.proto.storage.v1.StorageListFilesResponse.Builder.class);
    }

    // Construct using io.nitric.proto.storage.v1.StorageListFilesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFilesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (filesBuilder_ == null) {
        files_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        filesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.nitric.proto.storage.v1.Storages.internal_static_nitric_storage_v1_StorageListFilesResponse_descriptor;
    }

    @java.lang.Override
    public io.nitric.proto.storage.v1.StorageListFilesResponse getDefaultInstanceForType() {
      return io.nitric.proto.storage.v1.StorageListFilesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.nitric.proto.storage.v1.StorageListFilesResponse build() {
      io.nitric.proto.storage.v1.StorageListFilesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.nitric.proto.storage.v1.StorageListFilesResponse buildPartial() {
      io.nitric.proto.storage.v1.StorageListFilesResponse result = new io.nitric.proto.storage.v1.StorageListFilesResponse(this);
      int from_bitField0_ = bitField0_;
      if (filesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          files_ = java.util.Collections.unmodifiableList(files_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.files_ = files_;
      } else {
        result.files_ = filesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.nitric.proto.storage.v1.StorageListFilesResponse) {
        return mergeFrom((io.nitric.proto.storage.v1.StorageListFilesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.nitric.proto.storage.v1.StorageListFilesResponse other) {
      if (other == io.nitric.proto.storage.v1.StorageListFilesResponse.getDefaultInstance()) return this;
      if (filesBuilder_ == null) {
        if (!other.files_.isEmpty()) {
          if (files_.isEmpty()) {
            files_ = other.files_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFilesIsMutable();
            files_.addAll(other.files_);
          }
          onChanged();
        }
      } else {
        if (!other.files_.isEmpty()) {
          if (filesBuilder_.isEmpty()) {
            filesBuilder_.dispose();
            filesBuilder_ = null;
            files_ = other.files_;
            bitField0_ = (bitField0_ & ~0x00000001);
            filesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFilesFieldBuilder() : null;
          } else {
            filesBuilder_.addAllMessages(other.files_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.nitric.proto.storage.v1.StorageListFilesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.nitric.proto.storage.v1.StorageListFilesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.nitric.proto.storage.v1.File> files_ =
      java.util.Collections.emptyList();
    private void ensureFilesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        files_ = new java.util.ArrayList<io.nitric.proto.storage.v1.File>(files_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.nitric.proto.storage.v1.File, io.nitric.proto.storage.v1.File.Builder, io.nitric.proto.storage.v1.FileOrBuilder> filesBuilder_;

    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public java.util.List<io.nitric.proto.storage.v1.File> getFilesList() {
      if (filesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(files_);
      } else {
        return filesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public int getFilesCount() {
      if (filesBuilder_ == null) {
        return files_.size();
      } else {
        return filesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public io.nitric.proto.storage.v1.File getFiles(int index) {
      if (filesBuilder_ == null) {
        return files_.get(index);
      } else {
        return filesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder setFiles(
        int index, io.nitric.proto.storage.v1.File value) {
      if (filesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilesIsMutable();
        files_.set(index, value);
        onChanged();
      } else {
        filesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder setFiles(
        int index, io.nitric.proto.storage.v1.File.Builder builderForValue) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.set(index, builderForValue.build());
        onChanged();
      } else {
        filesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder addFiles(io.nitric.proto.storage.v1.File value) {
      if (filesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilesIsMutable();
        files_.add(value);
        onChanged();
      } else {
        filesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder addFiles(
        int index, io.nitric.proto.storage.v1.File value) {
      if (filesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilesIsMutable();
        files_.add(index, value);
        onChanged();
      } else {
        filesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder addFiles(
        io.nitric.proto.storage.v1.File.Builder builderForValue) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.add(builderForValue.build());
        onChanged();
      } else {
        filesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder addFiles(
        int index, io.nitric.proto.storage.v1.File.Builder builderForValue) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.add(index, builderForValue.build());
        onChanged();
      } else {
        filesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder addAllFiles(
        java.lang.Iterable<? extends io.nitric.proto.storage.v1.File> values) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, files_);
        onChanged();
      } else {
        filesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder clearFiles() {
      if (filesBuilder_ == null) {
        files_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        filesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public Builder removeFiles(int index) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.remove(index);
        onChanged();
      } else {
        filesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public io.nitric.proto.storage.v1.File.Builder getFilesBuilder(
        int index) {
      return getFilesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public io.nitric.proto.storage.v1.FileOrBuilder getFilesOrBuilder(
        int index) {
      if (filesBuilder_ == null) {
        return files_.get(index);  } else {
        return filesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public java.util.List<? extends io.nitric.proto.storage.v1.FileOrBuilder> 
         getFilesOrBuilderList() {
      if (filesBuilder_ != null) {
        return filesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(files_);
      }
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public io.nitric.proto.storage.v1.File.Builder addFilesBuilder() {
      return getFilesFieldBuilder().addBuilder(
          io.nitric.proto.storage.v1.File.getDefaultInstance());
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public io.nitric.proto.storage.v1.File.Builder addFilesBuilder(
        int index) {
      return getFilesFieldBuilder().addBuilder(
          index, io.nitric.proto.storage.v1.File.getDefaultInstance());
    }
    /**
     * <pre>
     * keys of the files in the bucket
     * </pre>
     *
     * <code>repeated .nitric.storage.v1.File files = 1;</code>
     */
    public java.util.List<io.nitric.proto.storage.v1.File.Builder> 
         getFilesBuilderList() {
      return getFilesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.nitric.proto.storage.v1.File, io.nitric.proto.storage.v1.File.Builder, io.nitric.proto.storage.v1.FileOrBuilder> 
        getFilesFieldBuilder() {
      if (filesBuilder_ == null) {
        filesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.nitric.proto.storage.v1.File, io.nitric.proto.storage.v1.File.Builder, io.nitric.proto.storage.v1.FileOrBuilder>(
                files_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        files_ = null;
      }
      return filesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nitric.storage.v1.StorageListFilesResponse)
  }

  // @@protoc_insertion_point(class_scope:nitric.storage.v1.StorageListFilesResponse)
  private static final io.nitric.proto.storage.v1.StorageListFilesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.nitric.proto.storage.v1.StorageListFilesResponse();
  }

  public static io.nitric.proto.storage.v1.StorageListFilesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StorageListFilesResponse>
      PARSER = new com.google.protobuf.AbstractParser<StorageListFilesResponse>() {
    @java.lang.Override
    public StorageListFilesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StorageListFilesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StorageListFilesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StorageListFilesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.nitric.proto.storage.v1.StorageListFilesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

