// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/storage/v1/storage.proto

package io.nitric.proto.storage.v1;

public interface StoragePreSignUrlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.storage.v1.StoragePreSignUrlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The pre-signed url, restricted to the operation, resource and expiry time specified in the request.
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * The pre-signed url, restricted to the operation, resource and expiry time specified in the request.
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
