// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/resource/v1/resource.proto

package io.nitric.proto.resource.v1;

public interface CollectionResourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.resource.v1.CollectionResource)
    com.google.protobuf.MessageOrBuilder {
}
