// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/resource/v1/resource.proto

package io.nitric.proto.resource.v1;

/**
 * Protobuf type {@code nitric.resource.v1.ResourceDeclareRequest}
 */
public final class ResourceDeclareRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nitric.resource.v1.ResourceDeclareRequest)
    ResourceDeclareRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceDeclareRequest.newBuilder() to construct.
  private ResourceDeclareRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceDeclareRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResourceDeclareRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceDeclareRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.nitric.proto.resource.v1.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(io.nitric.proto.resource.v1.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            io.nitric.proto.resource.v1.PolicyResource.Builder subBuilder = null;
            if (configCase_ == 10) {
              subBuilder = ((io.nitric.proto.resource.v1.PolicyResource) config_).toBuilder();
            }
            config_ =
                input.readMessage(io.nitric.proto.resource.v1.PolicyResource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.resource.v1.PolicyResource) config_);
              config_ = subBuilder.buildPartial();
            }
            configCase_ = 10;
            break;
          }
          case 90: {
            io.nitric.proto.resource.v1.BucketResource.Builder subBuilder = null;
            if (configCase_ == 11) {
              subBuilder = ((io.nitric.proto.resource.v1.BucketResource) config_).toBuilder();
            }
            config_ =
                input.readMessage(io.nitric.proto.resource.v1.BucketResource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.resource.v1.BucketResource) config_);
              config_ = subBuilder.buildPartial();
            }
            configCase_ = 11;
            break;
          }
          case 98: {
            io.nitric.proto.resource.v1.QueueResource.Builder subBuilder = null;
            if (configCase_ == 12) {
              subBuilder = ((io.nitric.proto.resource.v1.QueueResource) config_).toBuilder();
            }
            config_ =
                input.readMessage(io.nitric.proto.resource.v1.QueueResource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.resource.v1.QueueResource) config_);
              config_ = subBuilder.buildPartial();
            }
            configCase_ = 12;
            break;
          }
          case 106: {
            io.nitric.proto.resource.v1.TopicResource.Builder subBuilder = null;
            if (configCase_ == 13) {
              subBuilder = ((io.nitric.proto.resource.v1.TopicResource) config_).toBuilder();
            }
            config_ =
                input.readMessage(io.nitric.proto.resource.v1.TopicResource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.resource.v1.TopicResource) config_);
              config_ = subBuilder.buildPartial();
            }
            configCase_ = 13;
            break;
          }
          case 114: {
            io.nitric.proto.resource.v1.CollectionResource.Builder subBuilder = null;
            if (configCase_ == 14) {
              subBuilder = ((io.nitric.proto.resource.v1.CollectionResource) config_).toBuilder();
            }
            config_ =
                input.readMessage(io.nitric.proto.resource.v1.CollectionResource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.resource.v1.CollectionResource) config_);
              config_ = subBuilder.buildPartial();
            }
            configCase_ = 14;
            break;
          }
          case 122: {
            io.nitric.proto.resource.v1.SecretResource.Builder subBuilder = null;
            if (configCase_ == 15) {
              subBuilder = ((io.nitric.proto.resource.v1.SecretResource) config_).toBuilder();
            }
            config_ =
                input.readMessage(io.nitric.proto.resource.v1.SecretResource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.resource.v1.SecretResource) config_);
              config_ = subBuilder.buildPartial();
            }
            configCase_ = 15;
            break;
          }
          case 130: {
            io.nitric.proto.resource.v1.ApiResource.Builder subBuilder = null;
            if (configCase_ == 16) {
              subBuilder = ((io.nitric.proto.resource.v1.ApiResource) config_).toBuilder();
            }
            config_ =
                input.readMessage(io.nitric.proto.resource.v1.ApiResource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.nitric.proto.resource.v1.ApiResource) config_);
              config_ = subBuilder.buildPartial();
            }
            configCase_ = 16;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.nitric.proto.resource.v1.Resources.internal_static_nitric_resource_v1_ResourceDeclareRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.nitric.proto.resource.v1.Resources.internal_static_nitric_resource_v1_ResourceDeclareRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.nitric.proto.resource.v1.ResourceDeclareRequest.class, io.nitric.proto.resource.v1.ResourceDeclareRequest.Builder.class);
  }

  private int configCase_ = 0;
  private java.lang.Object config_;
  public enum ConfigCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    POLICY(10),
    BUCKET(11),
    QUEUE(12),
    TOPIC(13),
    COLLECTION(14),
    SECRET(15),
    API(16),
    CONFIG_NOT_SET(0);
    private final int value;
    private ConfigCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConfigCase valueOf(int value) {
      return forNumber(value);
    }

    public static ConfigCase forNumber(int value) {
      switch (value) {
        case 10: return POLICY;
        case 11: return BUCKET;
        case 12: return QUEUE;
        case 13: return TOPIC;
        case 14: return COLLECTION;
        case 15: return SECRET;
        case 16: return API;
        case 0: return CONFIG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ConfigCase
  getConfigCase() {
    return ConfigCase.forNumber(
        configCase_);
  }

  public static final int RESOURCE_FIELD_NUMBER = 1;
  private io.nitric.proto.resource.v1.Resource resource_;
  /**
   * <code>.nitric.resource.v1.Resource resource = 1;</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <code>.nitric.resource.v1.Resource resource = 1;</code>
   * @return The resource.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.Resource getResource() {
    return resource_ == null ? io.nitric.proto.resource.v1.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <code>.nitric.resource.v1.Resource resource = 1;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int POLICY_FIELD_NUMBER = 10;
  /**
   * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
   * @return Whether the policy field is set.
   */
  @java.lang.Override
  public boolean hasPolicy() {
    return configCase_ == 10;
  }
  /**
   * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
   * @return The policy.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.PolicyResource getPolicy() {
    if (configCase_ == 10) {
       return (io.nitric.proto.resource.v1.PolicyResource) config_;
    }
    return io.nitric.proto.resource.v1.PolicyResource.getDefaultInstance();
  }
  /**
   * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.PolicyResourceOrBuilder getPolicyOrBuilder() {
    if (configCase_ == 10) {
       return (io.nitric.proto.resource.v1.PolicyResource) config_;
    }
    return io.nitric.proto.resource.v1.PolicyResource.getDefaultInstance();
  }

  public static final int BUCKET_FIELD_NUMBER = 11;
  /**
   * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
   * @return Whether the bucket field is set.
   */
  @java.lang.Override
  public boolean hasBucket() {
    return configCase_ == 11;
  }
  /**
   * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
   * @return The bucket.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.BucketResource getBucket() {
    if (configCase_ == 11) {
       return (io.nitric.proto.resource.v1.BucketResource) config_;
    }
    return io.nitric.proto.resource.v1.BucketResource.getDefaultInstance();
  }
  /**
   * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.BucketResourceOrBuilder getBucketOrBuilder() {
    if (configCase_ == 11) {
       return (io.nitric.proto.resource.v1.BucketResource) config_;
    }
    return io.nitric.proto.resource.v1.BucketResource.getDefaultInstance();
  }

  public static final int QUEUE_FIELD_NUMBER = 12;
  /**
   * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
   * @return Whether the queue field is set.
   */
  @java.lang.Override
  public boolean hasQueue() {
    return configCase_ == 12;
  }
  /**
   * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
   * @return The queue.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.QueueResource getQueue() {
    if (configCase_ == 12) {
       return (io.nitric.proto.resource.v1.QueueResource) config_;
    }
    return io.nitric.proto.resource.v1.QueueResource.getDefaultInstance();
  }
  /**
   * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.QueueResourceOrBuilder getQueueOrBuilder() {
    if (configCase_ == 12) {
       return (io.nitric.proto.resource.v1.QueueResource) config_;
    }
    return io.nitric.proto.resource.v1.QueueResource.getDefaultInstance();
  }

  public static final int TOPIC_FIELD_NUMBER = 13;
  /**
   * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
   * @return Whether the topic field is set.
   */
  @java.lang.Override
  public boolean hasTopic() {
    return configCase_ == 13;
  }
  /**
   * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
   * @return The topic.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.TopicResource getTopic() {
    if (configCase_ == 13) {
       return (io.nitric.proto.resource.v1.TopicResource) config_;
    }
    return io.nitric.proto.resource.v1.TopicResource.getDefaultInstance();
  }
  /**
   * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.TopicResourceOrBuilder getTopicOrBuilder() {
    if (configCase_ == 13) {
       return (io.nitric.proto.resource.v1.TopicResource) config_;
    }
    return io.nitric.proto.resource.v1.TopicResource.getDefaultInstance();
  }

  public static final int COLLECTION_FIELD_NUMBER = 14;
  /**
   * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
   * @return Whether the collection field is set.
   */
  @java.lang.Override
  public boolean hasCollection() {
    return configCase_ == 14;
  }
  /**
   * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
   * @return The collection.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.CollectionResource getCollection() {
    if (configCase_ == 14) {
       return (io.nitric.proto.resource.v1.CollectionResource) config_;
    }
    return io.nitric.proto.resource.v1.CollectionResource.getDefaultInstance();
  }
  /**
   * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.CollectionResourceOrBuilder getCollectionOrBuilder() {
    if (configCase_ == 14) {
       return (io.nitric.proto.resource.v1.CollectionResource) config_;
    }
    return io.nitric.proto.resource.v1.CollectionResource.getDefaultInstance();
  }

  public static final int SECRET_FIELD_NUMBER = 15;
  /**
   * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
   * @return Whether the secret field is set.
   */
  @java.lang.Override
  public boolean hasSecret() {
    return configCase_ == 15;
  }
  /**
   * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
   * @return The secret.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.SecretResource getSecret() {
    if (configCase_ == 15) {
       return (io.nitric.proto.resource.v1.SecretResource) config_;
    }
    return io.nitric.proto.resource.v1.SecretResource.getDefaultInstance();
  }
  /**
   * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.SecretResourceOrBuilder getSecretOrBuilder() {
    if (configCase_ == 15) {
       return (io.nitric.proto.resource.v1.SecretResource) config_;
    }
    return io.nitric.proto.resource.v1.SecretResource.getDefaultInstance();
  }

  public static final int API_FIELD_NUMBER = 16;
  /**
   * <code>.nitric.resource.v1.ApiResource api = 16;</code>
   * @return Whether the api field is set.
   */
  @java.lang.Override
  public boolean hasApi() {
    return configCase_ == 16;
  }
  /**
   * <code>.nitric.resource.v1.ApiResource api = 16;</code>
   * @return The api.
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.ApiResource getApi() {
    if (configCase_ == 16) {
       return (io.nitric.proto.resource.v1.ApiResource) config_;
    }
    return io.nitric.proto.resource.v1.ApiResource.getDefaultInstance();
  }
  /**
   * <code>.nitric.resource.v1.ApiResource api = 16;</code>
   */
  @java.lang.Override
  public io.nitric.proto.resource.v1.ApiResourceOrBuilder getApiOrBuilder() {
    if (configCase_ == 16) {
       return (io.nitric.proto.resource.v1.ApiResource) config_;
    }
    return io.nitric.proto.resource.v1.ApiResource.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    if (configCase_ == 10) {
      output.writeMessage(10, (io.nitric.proto.resource.v1.PolicyResource) config_);
    }
    if (configCase_ == 11) {
      output.writeMessage(11, (io.nitric.proto.resource.v1.BucketResource) config_);
    }
    if (configCase_ == 12) {
      output.writeMessage(12, (io.nitric.proto.resource.v1.QueueResource) config_);
    }
    if (configCase_ == 13) {
      output.writeMessage(13, (io.nitric.proto.resource.v1.TopicResource) config_);
    }
    if (configCase_ == 14) {
      output.writeMessage(14, (io.nitric.proto.resource.v1.CollectionResource) config_);
    }
    if (configCase_ == 15) {
      output.writeMessage(15, (io.nitric.proto.resource.v1.SecretResource) config_);
    }
    if (configCase_ == 16) {
      output.writeMessage(16, (io.nitric.proto.resource.v1.ApiResource) config_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (configCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (io.nitric.proto.resource.v1.PolicyResource) config_);
    }
    if (configCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (io.nitric.proto.resource.v1.BucketResource) config_);
    }
    if (configCase_ == 12) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, (io.nitric.proto.resource.v1.QueueResource) config_);
    }
    if (configCase_ == 13) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, (io.nitric.proto.resource.v1.TopicResource) config_);
    }
    if (configCase_ == 14) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, (io.nitric.proto.resource.v1.CollectionResource) config_);
    }
    if (configCase_ == 15) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, (io.nitric.proto.resource.v1.SecretResource) config_);
    }
    if (configCase_ == 16) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, (io.nitric.proto.resource.v1.ApiResource) config_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.nitric.proto.resource.v1.ResourceDeclareRequest)) {
      return super.equals(obj);
    }
    io.nitric.proto.resource.v1.ResourceDeclareRequest other = (io.nitric.proto.resource.v1.ResourceDeclareRequest) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getConfigCase().equals(other.getConfigCase())) return false;
    switch (configCase_) {
      case 10:
        if (!getPolicy()
            .equals(other.getPolicy())) return false;
        break;
      case 11:
        if (!getBucket()
            .equals(other.getBucket())) return false;
        break;
      case 12:
        if (!getQueue()
            .equals(other.getQueue())) return false;
        break;
      case 13:
        if (!getTopic()
            .equals(other.getTopic())) return false;
        break;
      case 14:
        if (!getCollection()
            .equals(other.getCollection())) return false;
        break;
      case 15:
        if (!getSecret()
            .equals(other.getSecret())) return false;
        break;
      case 16:
        if (!getApi()
            .equals(other.getApi())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    switch (configCase_) {
      case 10:
        hash = (37 * hash) + POLICY_FIELD_NUMBER;
        hash = (53 * hash) + getPolicy().hashCode();
        break;
      case 11:
        hash = (37 * hash) + BUCKET_FIELD_NUMBER;
        hash = (53 * hash) + getBucket().hashCode();
        break;
      case 12:
        hash = (37 * hash) + QUEUE_FIELD_NUMBER;
        hash = (53 * hash) + getQueue().hashCode();
        break;
      case 13:
        hash = (37 * hash) + TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTopic().hashCode();
        break;
      case 14:
        hash = (37 * hash) + COLLECTION_FIELD_NUMBER;
        hash = (53 * hash) + getCollection().hashCode();
        break;
      case 15:
        hash = (37 * hash) + SECRET_FIELD_NUMBER;
        hash = (53 * hash) + getSecret().hashCode();
        break;
      case 16:
        hash = (37 * hash) + API_FIELD_NUMBER;
        hash = (53 * hash) + getApi().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.resource.v1.ResourceDeclareRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.nitric.proto.resource.v1.ResourceDeclareRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nitric.resource.v1.ResourceDeclareRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nitric.resource.v1.ResourceDeclareRequest)
      io.nitric.proto.resource.v1.ResourceDeclareRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nitric.proto.resource.v1.Resources.internal_static_nitric_resource_v1_ResourceDeclareRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nitric.proto.resource.v1.Resources.internal_static_nitric_resource_v1_ResourceDeclareRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nitric.proto.resource.v1.ResourceDeclareRequest.class, io.nitric.proto.resource.v1.ResourceDeclareRequest.Builder.class);
    }

    // Construct using io.nitric.proto.resource.v1.ResourceDeclareRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      configCase_ = 0;
      config_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.nitric.proto.resource.v1.Resources.internal_static_nitric_resource_v1_ResourceDeclareRequest_descriptor;
    }

    @java.lang.Override
    public io.nitric.proto.resource.v1.ResourceDeclareRequest getDefaultInstanceForType() {
      return io.nitric.proto.resource.v1.ResourceDeclareRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.nitric.proto.resource.v1.ResourceDeclareRequest build() {
      io.nitric.proto.resource.v1.ResourceDeclareRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.nitric.proto.resource.v1.ResourceDeclareRequest buildPartial() {
      io.nitric.proto.resource.v1.ResourceDeclareRequest result = new io.nitric.proto.resource.v1.ResourceDeclareRequest(this);
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      if (configCase_ == 10) {
        if (policyBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = policyBuilder_.build();
        }
      }
      if (configCase_ == 11) {
        if (bucketBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = bucketBuilder_.build();
        }
      }
      if (configCase_ == 12) {
        if (queueBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = queueBuilder_.build();
        }
      }
      if (configCase_ == 13) {
        if (topicBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = topicBuilder_.build();
        }
      }
      if (configCase_ == 14) {
        if (collectionBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = collectionBuilder_.build();
        }
      }
      if (configCase_ == 15) {
        if (secretBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = secretBuilder_.build();
        }
      }
      if (configCase_ == 16) {
        if (apiBuilder_ == null) {
          result.config_ = config_;
        } else {
          result.config_ = apiBuilder_.build();
        }
      }
      result.configCase_ = configCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.nitric.proto.resource.v1.ResourceDeclareRequest) {
        return mergeFrom((io.nitric.proto.resource.v1.ResourceDeclareRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.nitric.proto.resource.v1.ResourceDeclareRequest other) {
      if (other == io.nitric.proto.resource.v1.ResourceDeclareRequest.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      switch (other.getConfigCase()) {
        case POLICY: {
          mergePolicy(other.getPolicy());
          break;
        }
        case BUCKET: {
          mergeBucket(other.getBucket());
          break;
        }
        case QUEUE: {
          mergeQueue(other.getQueue());
          break;
        }
        case TOPIC: {
          mergeTopic(other.getTopic());
          break;
        }
        case COLLECTION: {
          mergeCollection(other.getCollection());
          break;
        }
        case SECRET: {
          mergeSecret(other.getSecret());
          break;
        }
        case API: {
          mergeApi(other.getApi());
          break;
        }
        case CONFIG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.nitric.proto.resource.v1.ResourceDeclareRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.nitric.proto.resource.v1.ResourceDeclareRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int configCase_ = 0;
    private java.lang.Object config_;
    public ConfigCase
        getConfigCase() {
      return ConfigCase.forNumber(
          configCase_);
    }

    public Builder clearConfig() {
      configCase_ = 0;
      config_ = null;
      onChanged();
      return this;
    }


    private io.nitric.proto.resource.v1.Resource resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.Resource, io.nitric.proto.resource.v1.Resource.Builder, io.nitric.proto.resource.v1.ResourceOrBuilder> resourceBuilder_;
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     * @return The resource.
     */
    public io.nitric.proto.resource.v1.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? io.nitric.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     */
    public Builder setResource(io.nitric.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     */
    public Builder setResource(
        io.nitric.proto.resource.v1.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     */
    public Builder mergeResource(io.nitric.proto.resource.v1.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            io.nitric.proto.resource.v1.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     */
    public io.nitric.proto.resource.v1.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     */
    public io.nitric.proto.resource.v1.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            io.nitric.proto.resource.v1.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>.nitric.resource.v1.Resource resource = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.Resource, io.nitric.proto.resource.v1.Resource.Builder, io.nitric.proto.resource.v1.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.Resource, io.nitric.proto.resource.v1.Resource.Builder, io.nitric.proto.resource.v1.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.PolicyResource, io.nitric.proto.resource.v1.PolicyResource.Builder, io.nitric.proto.resource.v1.PolicyResourceOrBuilder> policyBuilder_;
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     * @return Whether the policy field is set.
     */
    @java.lang.Override
    public boolean hasPolicy() {
      return configCase_ == 10;
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     * @return The policy.
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.PolicyResource getPolicy() {
      if (policyBuilder_ == null) {
        if (configCase_ == 10) {
          return (io.nitric.proto.resource.v1.PolicyResource) config_;
        }
        return io.nitric.proto.resource.v1.PolicyResource.getDefaultInstance();
      } else {
        if (configCase_ == 10) {
          return policyBuilder_.getMessage();
        }
        return io.nitric.proto.resource.v1.PolicyResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     */
    public Builder setPolicy(io.nitric.proto.resource.v1.PolicyResource value) {
      if (policyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        policyBuilder_.setMessage(value);
      }
      configCase_ = 10;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     */
    public Builder setPolicy(
        io.nitric.proto.resource.v1.PolicyResource.Builder builderForValue) {
      if (policyBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        policyBuilder_.setMessage(builderForValue.build());
      }
      configCase_ = 10;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     */
    public Builder mergePolicy(io.nitric.proto.resource.v1.PolicyResource value) {
      if (policyBuilder_ == null) {
        if (configCase_ == 10 &&
            config_ != io.nitric.proto.resource.v1.PolicyResource.getDefaultInstance()) {
          config_ = io.nitric.proto.resource.v1.PolicyResource.newBuilder((io.nitric.proto.resource.v1.PolicyResource) config_)
              .mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        if (configCase_ == 10) {
          policyBuilder_.mergeFrom(value);
        }
        policyBuilder_.setMessage(value);
      }
      configCase_ = 10;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     */
    public Builder clearPolicy() {
      if (policyBuilder_ == null) {
        if (configCase_ == 10) {
          configCase_ = 0;
          config_ = null;
          onChanged();
        }
      } else {
        if (configCase_ == 10) {
          configCase_ = 0;
          config_ = null;
        }
        policyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     */
    public io.nitric.proto.resource.v1.PolicyResource.Builder getPolicyBuilder() {
      return getPolicyFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.PolicyResourceOrBuilder getPolicyOrBuilder() {
      if ((configCase_ == 10) && (policyBuilder_ != null)) {
        return policyBuilder_.getMessageOrBuilder();
      } else {
        if (configCase_ == 10) {
          return (io.nitric.proto.resource.v1.PolicyResource) config_;
        }
        return io.nitric.proto.resource.v1.PolicyResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.PolicyResource policy = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.PolicyResource, io.nitric.proto.resource.v1.PolicyResource.Builder, io.nitric.proto.resource.v1.PolicyResourceOrBuilder> 
        getPolicyFieldBuilder() {
      if (policyBuilder_ == null) {
        if (!(configCase_ == 10)) {
          config_ = io.nitric.proto.resource.v1.PolicyResource.getDefaultInstance();
        }
        policyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.PolicyResource, io.nitric.proto.resource.v1.PolicyResource.Builder, io.nitric.proto.resource.v1.PolicyResourceOrBuilder>(
                (io.nitric.proto.resource.v1.PolicyResource) config_,
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      configCase_ = 10;
      onChanged();;
      return policyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.BucketResource, io.nitric.proto.resource.v1.BucketResource.Builder, io.nitric.proto.resource.v1.BucketResourceOrBuilder> bucketBuilder_;
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     * @return Whether the bucket field is set.
     */
    @java.lang.Override
    public boolean hasBucket() {
      return configCase_ == 11;
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     * @return The bucket.
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.BucketResource getBucket() {
      if (bucketBuilder_ == null) {
        if (configCase_ == 11) {
          return (io.nitric.proto.resource.v1.BucketResource) config_;
        }
        return io.nitric.proto.resource.v1.BucketResource.getDefaultInstance();
      } else {
        if (configCase_ == 11) {
          return bucketBuilder_.getMessage();
        }
        return io.nitric.proto.resource.v1.BucketResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     */
    public Builder setBucket(io.nitric.proto.resource.v1.BucketResource value) {
      if (bucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        bucketBuilder_.setMessage(value);
      }
      configCase_ = 11;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     */
    public Builder setBucket(
        io.nitric.proto.resource.v1.BucketResource.Builder builderForValue) {
      if (bucketBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        bucketBuilder_.setMessage(builderForValue.build());
      }
      configCase_ = 11;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     */
    public Builder mergeBucket(io.nitric.proto.resource.v1.BucketResource value) {
      if (bucketBuilder_ == null) {
        if (configCase_ == 11 &&
            config_ != io.nitric.proto.resource.v1.BucketResource.getDefaultInstance()) {
          config_ = io.nitric.proto.resource.v1.BucketResource.newBuilder((io.nitric.proto.resource.v1.BucketResource) config_)
              .mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        if (configCase_ == 11) {
          bucketBuilder_.mergeFrom(value);
        }
        bucketBuilder_.setMessage(value);
      }
      configCase_ = 11;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     */
    public Builder clearBucket() {
      if (bucketBuilder_ == null) {
        if (configCase_ == 11) {
          configCase_ = 0;
          config_ = null;
          onChanged();
        }
      } else {
        if (configCase_ == 11) {
          configCase_ = 0;
          config_ = null;
        }
        bucketBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     */
    public io.nitric.proto.resource.v1.BucketResource.Builder getBucketBuilder() {
      return getBucketFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.BucketResourceOrBuilder getBucketOrBuilder() {
      if ((configCase_ == 11) && (bucketBuilder_ != null)) {
        return bucketBuilder_.getMessageOrBuilder();
      } else {
        if (configCase_ == 11) {
          return (io.nitric.proto.resource.v1.BucketResource) config_;
        }
        return io.nitric.proto.resource.v1.BucketResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.BucketResource bucket = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.BucketResource, io.nitric.proto.resource.v1.BucketResource.Builder, io.nitric.proto.resource.v1.BucketResourceOrBuilder> 
        getBucketFieldBuilder() {
      if (bucketBuilder_ == null) {
        if (!(configCase_ == 11)) {
          config_ = io.nitric.proto.resource.v1.BucketResource.getDefaultInstance();
        }
        bucketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.BucketResource, io.nitric.proto.resource.v1.BucketResource.Builder, io.nitric.proto.resource.v1.BucketResourceOrBuilder>(
                (io.nitric.proto.resource.v1.BucketResource) config_,
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      configCase_ = 11;
      onChanged();;
      return bucketBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.QueueResource, io.nitric.proto.resource.v1.QueueResource.Builder, io.nitric.proto.resource.v1.QueueResourceOrBuilder> queueBuilder_;
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     * @return Whether the queue field is set.
     */
    @java.lang.Override
    public boolean hasQueue() {
      return configCase_ == 12;
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     * @return The queue.
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.QueueResource getQueue() {
      if (queueBuilder_ == null) {
        if (configCase_ == 12) {
          return (io.nitric.proto.resource.v1.QueueResource) config_;
        }
        return io.nitric.proto.resource.v1.QueueResource.getDefaultInstance();
      } else {
        if (configCase_ == 12) {
          return queueBuilder_.getMessage();
        }
        return io.nitric.proto.resource.v1.QueueResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     */
    public Builder setQueue(io.nitric.proto.resource.v1.QueueResource value) {
      if (queueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        queueBuilder_.setMessage(value);
      }
      configCase_ = 12;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     */
    public Builder setQueue(
        io.nitric.proto.resource.v1.QueueResource.Builder builderForValue) {
      if (queueBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        queueBuilder_.setMessage(builderForValue.build());
      }
      configCase_ = 12;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     */
    public Builder mergeQueue(io.nitric.proto.resource.v1.QueueResource value) {
      if (queueBuilder_ == null) {
        if (configCase_ == 12 &&
            config_ != io.nitric.proto.resource.v1.QueueResource.getDefaultInstance()) {
          config_ = io.nitric.proto.resource.v1.QueueResource.newBuilder((io.nitric.proto.resource.v1.QueueResource) config_)
              .mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        if (configCase_ == 12) {
          queueBuilder_.mergeFrom(value);
        }
        queueBuilder_.setMessage(value);
      }
      configCase_ = 12;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     */
    public Builder clearQueue() {
      if (queueBuilder_ == null) {
        if (configCase_ == 12) {
          configCase_ = 0;
          config_ = null;
          onChanged();
        }
      } else {
        if (configCase_ == 12) {
          configCase_ = 0;
          config_ = null;
        }
        queueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     */
    public io.nitric.proto.resource.v1.QueueResource.Builder getQueueBuilder() {
      return getQueueFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.QueueResourceOrBuilder getQueueOrBuilder() {
      if ((configCase_ == 12) && (queueBuilder_ != null)) {
        return queueBuilder_.getMessageOrBuilder();
      } else {
        if (configCase_ == 12) {
          return (io.nitric.proto.resource.v1.QueueResource) config_;
        }
        return io.nitric.proto.resource.v1.QueueResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.QueueResource queue = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.QueueResource, io.nitric.proto.resource.v1.QueueResource.Builder, io.nitric.proto.resource.v1.QueueResourceOrBuilder> 
        getQueueFieldBuilder() {
      if (queueBuilder_ == null) {
        if (!(configCase_ == 12)) {
          config_ = io.nitric.proto.resource.v1.QueueResource.getDefaultInstance();
        }
        queueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.QueueResource, io.nitric.proto.resource.v1.QueueResource.Builder, io.nitric.proto.resource.v1.QueueResourceOrBuilder>(
                (io.nitric.proto.resource.v1.QueueResource) config_,
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      configCase_ = 12;
      onChanged();;
      return queueBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.TopicResource, io.nitric.proto.resource.v1.TopicResource.Builder, io.nitric.proto.resource.v1.TopicResourceOrBuilder> topicBuilder_;
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     * @return Whether the topic field is set.
     */
    @java.lang.Override
    public boolean hasTopic() {
      return configCase_ == 13;
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     * @return The topic.
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.TopicResource getTopic() {
      if (topicBuilder_ == null) {
        if (configCase_ == 13) {
          return (io.nitric.proto.resource.v1.TopicResource) config_;
        }
        return io.nitric.proto.resource.v1.TopicResource.getDefaultInstance();
      } else {
        if (configCase_ == 13) {
          return topicBuilder_.getMessage();
        }
        return io.nitric.proto.resource.v1.TopicResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     */
    public Builder setTopic(io.nitric.proto.resource.v1.TopicResource value) {
      if (topicBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        topicBuilder_.setMessage(value);
      }
      configCase_ = 13;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     */
    public Builder setTopic(
        io.nitric.proto.resource.v1.TopicResource.Builder builderForValue) {
      if (topicBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        topicBuilder_.setMessage(builderForValue.build());
      }
      configCase_ = 13;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     */
    public Builder mergeTopic(io.nitric.proto.resource.v1.TopicResource value) {
      if (topicBuilder_ == null) {
        if (configCase_ == 13 &&
            config_ != io.nitric.proto.resource.v1.TopicResource.getDefaultInstance()) {
          config_ = io.nitric.proto.resource.v1.TopicResource.newBuilder((io.nitric.proto.resource.v1.TopicResource) config_)
              .mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        if (configCase_ == 13) {
          topicBuilder_.mergeFrom(value);
        }
        topicBuilder_.setMessage(value);
      }
      configCase_ = 13;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     */
    public Builder clearTopic() {
      if (topicBuilder_ == null) {
        if (configCase_ == 13) {
          configCase_ = 0;
          config_ = null;
          onChanged();
        }
      } else {
        if (configCase_ == 13) {
          configCase_ = 0;
          config_ = null;
        }
        topicBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     */
    public io.nitric.proto.resource.v1.TopicResource.Builder getTopicBuilder() {
      return getTopicFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.TopicResourceOrBuilder getTopicOrBuilder() {
      if ((configCase_ == 13) && (topicBuilder_ != null)) {
        return topicBuilder_.getMessageOrBuilder();
      } else {
        if (configCase_ == 13) {
          return (io.nitric.proto.resource.v1.TopicResource) config_;
        }
        return io.nitric.proto.resource.v1.TopicResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.TopicResource topic = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.TopicResource, io.nitric.proto.resource.v1.TopicResource.Builder, io.nitric.proto.resource.v1.TopicResourceOrBuilder> 
        getTopicFieldBuilder() {
      if (topicBuilder_ == null) {
        if (!(configCase_ == 13)) {
          config_ = io.nitric.proto.resource.v1.TopicResource.getDefaultInstance();
        }
        topicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.TopicResource, io.nitric.proto.resource.v1.TopicResource.Builder, io.nitric.proto.resource.v1.TopicResourceOrBuilder>(
                (io.nitric.proto.resource.v1.TopicResource) config_,
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      configCase_ = 13;
      onChanged();;
      return topicBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.CollectionResource, io.nitric.proto.resource.v1.CollectionResource.Builder, io.nitric.proto.resource.v1.CollectionResourceOrBuilder> collectionBuilder_;
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     * @return Whether the collection field is set.
     */
    @java.lang.Override
    public boolean hasCollection() {
      return configCase_ == 14;
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     * @return The collection.
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.CollectionResource getCollection() {
      if (collectionBuilder_ == null) {
        if (configCase_ == 14) {
          return (io.nitric.proto.resource.v1.CollectionResource) config_;
        }
        return io.nitric.proto.resource.v1.CollectionResource.getDefaultInstance();
      } else {
        if (configCase_ == 14) {
          return collectionBuilder_.getMessage();
        }
        return io.nitric.proto.resource.v1.CollectionResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     */
    public Builder setCollection(io.nitric.proto.resource.v1.CollectionResource value) {
      if (collectionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        collectionBuilder_.setMessage(value);
      }
      configCase_ = 14;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     */
    public Builder setCollection(
        io.nitric.proto.resource.v1.CollectionResource.Builder builderForValue) {
      if (collectionBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        collectionBuilder_.setMessage(builderForValue.build());
      }
      configCase_ = 14;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     */
    public Builder mergeCollection(io.nitric.proto.resource.v1.CollectionResource value) {
      if (collectionBuilder_ == null) {
        if (configCase_ == 14 &&
            config_ != io.nitric.proto.resource.v1.CollectionResource.getDefaultInstance()) {
          config_ = io.nitric.proto.resource.v1.CollectionResource.newBuilder((io.nitric.proto.resource.v1.CollectionResource) config_)
              .mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        if (configCase_ == 14) {
          collectionBuilder_.mergeFrom(value);
        }
        collectionBuilder_.setMessage(value);
      }
      configCase_ = 14;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     */
    public Builder clearCollection() {
      if (collectionBuilder_ == null) {
        if (configCase_ == 14) {
          configCase_ = 0;
          config_ = null;
          onChanged();
        }
      } else {
        if (configCase_ == 14) {
          configCase_ = 0;
          config_ = null;
        }
        collectionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     */
    public io.nitric.proto.resource.v1.CollectionResource.Builder getCollectionBuilder() {
      return getCollectionFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.CollectionResourceOrBuilder getCollectionOrBuilder() {
      if ((configCase_ == 14) && (collectionBuilder_ != null)) {
        return collectionBuilder_.getMessageOrBuilder();
      } else {
        if (configCase_ == 14) {
          return (io.nitric.proto.resource.v1.CollectionResource) config_;
        }
        return io.nitric.proto.resource.v1.CollectionResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.CollectionResource collection = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.CollectionResource, io.nitric.proto.resource.v1.CollectionResource.Builder, io.nitric.proto.resource.v1.CollectionResourceOrBuilder> 
        getCollectionFieldBuilder() {
      if (collectionBuilder_ == null) {
        if (!(configCase_ == 14)) {
          config_ = io.nitric.proto.resource.v1.CollectionResource.getDefaultInstance();
        }
        collectionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.CollectionResource, io.nitric.proto.resource.v1.CollectionResource.Builder, io.nitric.proto.resource.v1.CollectionResourceOrBuilder>(
                (io.nitric.proto.resource.v1.CollectionResource) config_,
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      configCase_ = 14;
      onChanged();;
      return collectionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.SecretResource, io.nitric.proto.resource.v1.SecretResource.Builder, io.nitric.proto.resource.v1.SecretResourceOrBuilder> secretBuilder_;
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     * @return Whether the secret field is set.
     */
    @java.lang.Override
    public boolean hasSecret() {
      return configCase_ == 15;
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     * @return The secret.
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.SecretResource getSecret() {
      if (secretBuilder_ == null) {
        if (configCase_ == 15) {
          return (io.nitric.proto.resource.v1.SecretResource) config_;
        }
        return io.nitric.proto.resource.v1.SecretResource.getDefaultInstance();
      } else {
        if (configCase_ == 15) {
          return secretBuilder_.getMessage();
        }
        return io.nitric.proto.resource.v1.SecretResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     */
    public Builder setSecret(io.nitric.proto.resource.v1.SecretResource value) {
      if (secretBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        secretBuilder_.setMessage(value);
      }
      configCase_ = 15;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     */
    public Builder setSecret(
        io.nitric.proto.resource.v1.SecretResource.Builder builderForValue) {
      if (secretBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        secretBuilder_.setMessage(builderForValue.build());
      }
      configCase_ = 15;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     */
    public Builder mergeSecret(io.nitric.proto.resource.v1.SecretResource value) {
      if (secretBuilder_ == null) {
        if (configCase_ == 15 &&
            config_ != io.nitric.proto.resource.v1.SecretResource.getDefaultInstance()) {
          config_ = io.nitric.proto.resource.v1.SecretResource.newBuilder((io.nitric.proto.resource.v1.SecretResource) config_)
              .mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        if (configCase_ == 15) {
          secretBuilder_.mergeFrom(value);
        }
        secretBuilder_.setMessage(value);
      }
      configCase_ = 15;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     */
    public Builder clearSecret() {
      if (secretBuilder_ == null) {
        if (configCase_ == 15) {
          configCase_ = 0;
          config_ = null;
          onChanged();
        }
      } else {
        if (configCase_ == 15) {
          configCase_ = 0;
          config_ = null;
        }
        secretBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     */
    public io.nitric.proto.resource.v1.SecretResource.Builder getSecretBuilder() {
      return getSecretFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.SecretResourceOrBuilder getSecretOrBuilder() {
      if ((configCase_ == 15) && (secretBuilder_ != null)) {
        return secretBuilder_.getMessageOrBuilder();
      } else {
        if (configCase_ == 15) {
          return (io.nitric.proto.resource.v1.SecretResource) config_;
        }
        return io.nitric.proto.resource.v1.SecretResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.SecretResource secret = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.SecretResource, io.nitric.proto.resource.v1.SecretResource.Builder, io.nitric.proto.resource.v1.SecretResourceOrBuilder> 
        getSecretFieldBuilder() {
      if (secretBuilder_ == null) {
        if (!(configCase_ == 15)) {
          config_ = io.nitric.proto.resource.v1.SecretResource.getDefaultInstance();
        }
        secretBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.SecretResource, io.nitric.proto.resource.v1.SecretResource.Builder, io.nitric.proto.resource.v1.SecretResourceOrBuilder>(
                (io.nitric.proto.resource.v1.SecretResource) config_,
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      configCase_ = 15;
      onChanged();;
      return secretBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.ApiResource, io.nitric.proto.resource.v1.ApiResource.Builder, io.nitric.proto.resource.v1.ApiResourceOrBuilder> apiBuilder_;
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     * @return Whether the api field is set.
     */
    @java.lang.Override
    public boolean hasApi() {
      return configCase_ == 16;
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     * @return The api.
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.ApiResource getApi() {
      if (apiBuilder_ == null) {
        if (configCase_ == 16) {
          return (io.nitric.proto.resource.v1.ApiResource) config_;
        }
        return io.nitric.proto.resource.v1.ApiResource.getDefaultInstance();
      } else {
        if (configCase_ == 16) {
          return apiBuilder_.getMessage();
        }
        return io.nitric.proto.resource.v1.ApiResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     */
    public Builder setApi(io.nitric.proto.resource.v1.ApiResource value) {
      if (apiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        apiBuilder_.setMessage(value);
      }
      configCase_ = 16;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     */
    public Builder setApi(
        io.nitric.proto.resource.v1.ApiResource.Builder builderForValue) {
      if (apiBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        apiBuilder_.setMessage(builderForValue.build());
      }
      configCase_ = 16;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     */
    public Builder mergeApi(io.nitric.proto.resource.v1.ApiResource value) {
      if (apiBuilder_ == null) {
        if (configCase_ == 16 &&
            config_ != io.nitric.proto.resource.v1.ApiResource.getDefaultInstance()) {
          config_ = io.nitric.proto.resource.v1.ApiResource.newBuilder((io.nitric.proto.resource.v1.ApiResource) config_)
              .mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        if (configCase_ == 16) {
          apiBuilder_.mergeFrom(value);
        }
        apiBuilder_.setMessage(value);
      }
      configCase_ = 16;
      return this;
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     */
    public Builder clearApi() {
      if (apiBuilder_ == null) {
        if (configCase_ == 16) {
          configCase_ = 0;
          config_ = null;
          onChanged();
        }
      } else {
        if (configCase_ == 16) {
          configCase_ = 0;
          config_ = null;
        }
        apiBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     */
    public io.nitric.proto.resource.v1.ApiResource.Builder getApiBuilder() {
      return getApiFieldBuilder().getBuilder();
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     */
    @java.lang.Override
    public io.nitric.proto.resource.v1.ApiResourceOrBuilder getApiOrBuilder() {
      if ((configCase_ == 16) && (apiBuilder_ != null)) {
        return apiBuilder_.getMessageOrBuilder();
      } else {
        if (configCase_ == 16) {
          return (io.nitric.proto.resource.v1.ApiResource) config_;
        }
        return io.nitric.proto.resource.v1.ApiResource.getDefaultInstance();
      }
    }
    /**
     * <code>.nitric.resource.v1.ApiResource api = 16;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.nitric.proto.resource.v1.ApiResource, io.nitric.proto.resource.v1.ApiResource.Builder, io.nitric.proto.resource.v1.ApiResourceOrBuilder> 
        getApiFieldBuilder() {
      if (apiBuilder_ == null) {
        if (!(configCase_ == 16)) {
          config_ = io.nitric.proto.resource.v1.ApiResource.getDefaultInstance();
        }
        apiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.nitric.proto.resource.v1.ApiResource, io.nitric.proto.resource.v1.ApiResource.Builder, io.nitric.proto.resource.v1.ApiResourceOrBuilder>(
                (io.nitric.proto.resource.v1.ApiResource) config_,
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      configCase_ = 16;
      onChanged();;
      return apiBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nitric.resource.v1.ResourceDeclareRequest)
  }

  // @@protoc_insertion_point(class_scope:nitric.resource.v1.ResourceDeclareRequest)
  private static final io.nitric.proto.resource.v1.ResourceDeclareRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.nitric.proto.resource.v1.ResourceDeclareRequest();
  }

  public static io.nitric.proto.resource.v1.ResourceDeclareRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceDeclareRequest>
      PARSER = new com.google.protobuf.AbstractParser<ResourceDeclareRequest>() {
    @java.lang.Override
    public ResourceDeclareRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceDeclareRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceDeclareRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceDeclareRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.nitric.proto.resource.v1.ResourceDeclareRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

