// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/secret/v1/secret.proto

package io.nitric.proto.secret.v1;

public interface SecretVersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.secret.v1.SecretVersion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Reference to the secret container 
   * </pre>
   *
   * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
   * @return Whether the secret field is set.
   */
  boolean hasSecret();
  /**
   * <pre>
   * Reference to the secret container 
   * </pre>
   *
   * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
   * @return The secret.
   */
  io.nitric.proto.secret.v1.Secret getSecret();
  /**
   * <pre>
   * Reference to the secret container 
   * </pre>
   *
   * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
   */
  io.nitric.proto.secret.v1.SecretOrBuilder getSecretOrBuilder();

  /**
   * <pre>
   * The secret version
   * </pre>
   *
   * <code>string version = 2 [(.validate.rules) = { ... }</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * The secret version
   * </pre>
   *
   * <code>string version = 2 [(.validate.rules) = { ... }</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
