// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/secret/v1/secret.proto

package io.nitric.proto.secret.v1;

public interface SecretPutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.secret.v1.SecretPutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The Secret to put to the Secret store
   * </pre>
   *
   * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
   * @return Whether the secret field is set.
   */
  boolean hasSecret();
  /**
   * <pre>
   * The Secret to put to the Secret store
   * </pre>
   *
   * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
   * @return The secret.
   */
  io.nitric.proto.secret.v1.Secret getSecret();
  /**
   * <pre>
   * The Secret to put to the Secret store
   * </pre>
   *
   * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
   */
  io.nitric.proto.secret.v1.SecretOrBuilder getSecretOrBuilder();

  /**
   * <pre>
   * The value to assign to that secret
   * </pre>
   *
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
