// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/faas/v1/faas.proto

package io.nitric.proto.faas.v1;

public final class NitricFaas {
  private NitricFaas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ApiWorkerScopes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ApiWorkerScopes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ApiWorkerOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ApiWorkerOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ApiWorkerOptions_SecurityEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ApiWorkerOptions_SecurityEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ApiWorker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ApiWorker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_SubscriptionWorker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_SubscriptionWorker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ScheduleWorker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ScheduleWorker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ScheduleRate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ScheduleRate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_ScheduleCron_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_ScheduleCron_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_InitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_InitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_InitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_InitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TriggerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TriggerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HeaderValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HeaderValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_QueryValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_QueryValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersOldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_HeadersOldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsOldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsOldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpTriggerContext_PathParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpTriggerContext_PathParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TopicTriggerContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TopicTriggerContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TriggerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TriggerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpResponseContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpResponseContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersOldEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpResponseContext_HeadersOldEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nitric_faas_v1_TopicResponseContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nitric_faas_v1_TopicResponseContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/faas/v1/faas.proto\022\016nitric.faas." +
      "v1\"\230\001\n\rClientMessage\022\n\n\002id\030\001 \001(\t\0223\n\014init" +
      "_request\030\002 \001(\0132\033.nitric.faas.v1.InitRequ" +
      "estH\000\022;\n\020trigger_response\030\003 \001(\0132\037.nitric" +
      ".faas.v1.TriggerResponseH\000B\t\n\007content\"\230\001" +
      "\n\rServerMessage\022\n\n\002id\030\001 \001(\t\0225\n\rinit_resp" +
      "onse\030\002 \001(\0132\034.nitric.faas.v1.InitResponse" +
      "H\000\0229\n\017trigger_request\030\003 \001(\0132\036.nitric.faa" +
      "s.v1.TriggerRequestH\000B\t\n\007content\"!\n\017ApiW" +
      "orkerScopes\022\016\n\006scopes\030\001 \003(\t\"\301\001\n\020ApiWorke" +
      "rOptions\022@\n\010security\030\001 \003(\0132..nitric.faas" +
      ".v1.ApiWorkerOptions.SecurityEntry\022\031\n\021se" +
      "curity_disabled\030\002 \001(\010\032P\n\rSecurityEntry\022\013" +
      "\n\003key\030\001 \001(\t\022.\n\005value\030\002 \001(\0132\037.nitric.faas" +
      ".v1.ApiWorkerScopes:\0028\001\"j\n\tApiWorker\022\013\n\003" +
      "api\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\022\017\n\007methods\030\003 \003(\t" +
      "\0221\n\007options\030\004 \001(\0132 .nitric.faas.v1.ApiWo" +
      "rkerOptions\"#\n\022SubscriptionWorker\022\r\n\005top" +
      "ic\030\001 \001(\t\"\204\001\n\016ScheduleWorker\022\013\n\003key\030\001 \001(\t" +
      "\022,\n\004rate\030\n \001(\0132\034.nitric.faas.v1.Schedule" +
      "RateH\000\022,\n\004cron\030\013 \001(\0132\034.nitric.faas.v1.Sc" +
      "heduleCronH\000B\t\n\007cadence\"\034\n\014ScheduleRate\022" +
      "\014\n\004rate\030\001 \001(\t\"\034\n\014ScheduleCron\022\014\n\004cron\030\001 " +
      "\001(\t\"\261\001\n\013InitRequest\022(\n\003api\030\n \001(\0132\031.nitri" +
      "c.faas.v1.ApiWorkerH\000\022:\n\014subscription\030\013 " +
      "\001(\0132\".nitric.faas.v1.SubscriptionWorkerH" +
      "\000\0222\n\010schedule\030\014 \001(\0132\036.nitric.faas.v1.Sch" +
      "eduleWorkerH\000B\010\n\006Worker\"\016\n\014InitResponse\"" +
      "\246\001\n\016TriggerRequest\022\014\n\004data\030\001 \001(\014\022\021\n\tmime" +
      "_type\030\002 \001(\t\0222\n\004http\030\003 \001(\0132\".nitric.faas." +
      "v1.HttpTriggerContextH\000\0224\n\005topic\030\004 \001(\0132#" +
      ".nitric.faas.v1.TopicTriggerContextH\000B\t\n" +
      "\007context\"\034\n\013HeaderValue\022\r\n\005value\030\001 \003(\t\"\033" +
      "\n\nQueryValue\022\r\n\005value\030\001 \003(\t\"\345\005\n\022HttpTrig" +
      "gerContext\022\016\n\006method\030\001 \001(\t\022\014\n\004path\030\002 \001(\t" +
      "\022K\n\013headers_old\030\003 \003(\01322.nitric.faas.v1.H" +
      "ttpTriggerContext.HeadersOldEntryB\002\030\001\022T\n" +
      "\020query_params_old\030\004 \003(\01326.nitric.faas.v1" +
      ".HttpTriggerContext.QueryParamsOldEntryB" +
      "\002\030\001\022@\n\007headers\030\005 \003(\0132/.nitric.faas.v1.Ht" +
      "tpTriggerContext.HeadersEntry\022I\n\014query_p" +
      "arams\030\006 \003(\01323.nitric.faas.v1.HttpTrigger" +
      "Context.QueryParamsEntry\022G\n\013path_params\030" +
      "\007 \003(\01322.nitric.faas.v1.HttpTriggerContex" +
      "t.PathParamsEntry\0321\n\017HeadersOldEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0325\n\023QueryPar" +
      "amsOldEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\032K\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022*\n\005valu" +
      "e\030\002 \001(\0132\033.nitric.faas.v1.HeaderValue:\0028\001" +
      "\032N\n\020QueryParamsEntry\022\013\n\003key\030\001 \001(\t\022)\n\005val" +
      "ue\030\002 \001(\0132\032.nitric.faas.v1.QueryValue:\0028\001" +
      "\0321\n\017PathParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"$\n\023TopicTriggerContext\022\r\n\005to" +
      "pic\030\001 \001(\t\"\226\001\n\017TriggerResponse\022\014\n\004data\030\001 " +
      "\001(\014\0223\n\004http\030\n \001(\0132#.nitric.faas.v1.HttpR" +
      "esponseContextH\000\0225\n\005topic\030\013 \001(\0132$.nitric" +
      ".faas.v1.TopicResponseContextH\000B\t\n\007conte" +
      "xt\"\266\002\n\023HttpResponseContext\022L\n\013headers_ol" +
      "d\030\001 \003(\01323.nitric.faas.v1.HttpResponseCon" +
      "text.HeadersOldEntryB\002\030\001\022\016\n\006status\030\002 \001(\005" +
      "\022A\n\007headers\030\003 \003(\01320.nitric.faas.v1.HttpR" +
      "esponseContext.HeadersEntry\0321\n\017HeadersOl" +
      "dEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032K" +
      "\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022*\n\005value\030\002 \001" +
      "(\0132\033.nitric.faas.v1.HeaderValue:\0028\001\"\'\n\024T" +
      "opicResponseContext\022\017\n\007success\030\001 \001(\0102`\n\013" +
      "FaasService\022Q\n\rTriggerStream\022\035.nitric.fa" +
      "as.v1.ClientMessage\032\035.nitric.faas.v1.Ser" +
      "verMessage(\0010\001Bc\n\027io.nitric.proto.faas.v" +
      "1B\nNitricFaasP\001Z\014nitric/v1;v1\252\002\024Nitric.P" +
      "roto.Faas.v1\312\002\024Nitric\\Proto\\Faas\\V1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nitric_faas_v1_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nitric_faas_v1_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ClientMessage_descriptor,
        new java.lang.String[] { "Id", "InitRequest", "TriggerResponse", "Content", });
    internal_static_nitric_faas_v1_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nitric_faas_v1_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ServerMessage_descriptor,
        new java.lang.String[] { "Id", "InitResponse", "TriggerRequest", "Content", });
    internal_static_nitric_faas_v1_ApiWorkerScopes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nitric_faas_v1_ApiWorkerScopes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ApiWorkerScopes_descriptor,
        new java.lang.String[] { "Scopes", });
    internal_static_nitric_faas_v1_ApiWorkerOptions_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_nitric_faas_v1_ApiWorkerOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ApiWorkerOptions_descriptor,
        new java.lang.String[] { "Security", "SecurityDisabled", });
    internal_static_nitric_faas_v1_ApiWorkerOptions_SecurityEntry_descriptor =
      internal_static_nitric_faas_v1_ApiWorkerOptions_descriptor.getNestedTypes().get(0);
    internal_static_nitric_faas_v1_ApiWorkerOptions_SecurityEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ApiWorkerOptions_SecurityEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_ApiWorker_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_nitric_faas_v1_ApiWorker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ApiWorker_descriptor,
        new java.lang.String[] { "Api", "Path", "Methods", "Options", });
    internal_static_nitric_faas_v1_SubscriptionWorker_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_nitric_faas_v1_SubscriptionWorker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_SubscriptionWorker_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_nitric_faas_v1_ScheduleWorker_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_nitric_faas_v1_ScheduleWorker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ScheduleWorker_descriptor,
        new java.lang.String[] { "Key", "Rate", "Cron", "Cadence", });
    internal_static_nitric_faas_v1_ScheduleRate_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_nitric_faas_v1_ScheduleRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ScheduleRate_descriptor,
        new java.lang.String[] { "Rate", });
    internal_static_nitric_faas_v1_ScheduleCron_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_nitric_faas_v1_ScheduleCron_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_ScheduleCron_descriptor,
        new java.lang.String[] { "Cron", });
    internal_static_nitric_faas_v1_InitRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_nitric_faas_v1_InitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_InitRequest_descriptor,
        new java.lang.String[] { "Api", "Subscription", "Schedule", "Worker", });
    internal_static_nitric_faas_v1_InitResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_nitric_faas_v1_InitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_InitResponse_descriptor,
        new java.lang.String[] { });
    internal_static_nitric_faas_v1_TriggerRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_nitric_faas_v1_TriggerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TriggerRequest_descriptor,
        new java.lang.String[] { "Data", "MimeType", "Http", "Topic", "Context", });
    internal_static_nitric_faas_v1_HeaderValue_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_nitric_faas_v1_HeaderValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HeaderValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_nitric_faas_v1_QueryValue_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_nitric_faas_v1_QueryValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_QueryValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_nitric_faas_v1_HttpTriggerContext_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_nitric_faas_v1_HttpTriggerContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_descriptor,
        new java.lang.String[] { "Method", "Path", "HeadersOld", "QueryParamsOld", "Headers", "QueryParams", "PathParams", });
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersOldEntry_descriptor =
      internal_static_nitric_faas_v1_HttpTriggerContext_descriptor.getNestedTypes().get(0);
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersOldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_HeadersOldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsOldEntry_descriptor =
      internal_static_nitric_faas_v1_HttpTriggerContext_descriptor.getNestedTypes().get(1);
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsOldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsOldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_descriptor =
      internal_static_nitric_faas_v1_HttpTriggerContext_descriptor.getNestedTypes().get(2);
    internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_descriptor =
      internal_static_nitric_faas_v1_HttpTriggerContext_descriptor.getNestedTypes().get(3);
    internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_QueryParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_HttpTriggerContext_PathParamsEntry_descriptor =
      internal_static_nitric_faas_v1_HttpTriggerContext_descriptor.getNestedTypes().get(4);
    internal_static_nitric_faas_v1_HttpTriggerContext_PathParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpTriggerContext_PathParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_TopicTriggerContext_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_nitric_faas_v1_TopicTriggerContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TopicTriggerContext_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_nitric_faas_v1_TriggerResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_nitric_faas_v1_TriggerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TriggerResponse_descriptor,
        new java.lang.String[] { "Data", "Http", "Topic", "Context", });
    internal_static_nitric_faas_v1_HttpResponseContext_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_nitric_faas_v1_HttpResponseContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpResponseContext_descriptor,
        new java.lang.String[] { "HeadersOld", "Status", "Headers", });
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersOldEntry_descriptor =
      internal_static_nitric_faas_v1_HttpResponseContext_descriptor.getNestedTypes().get(0);
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersOldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpResponseContext_HeadersOldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_descriptor =
      internal_static_nitric_faas_v1_HttpResponseContext_descriptor.getNestedTypes().get(1);
    internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_HttpResponseContext_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_nitric_faas_v1_TopicResponseContext_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_nitric_faas_v1_TopicResponseContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nitric_faas_v1_TopicResponseContext_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
